name: Hashnode Blog Updater

# Controls when the workflow will run
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  update_blogs:
    name: "Update Blogs"
    runs-on: ubuntu-latest
    steps:
      - name: "📥  Fetching Repository Contents"
        uses: actions/checkout@main

      - name: "📚  Hashnode Updater"
        uses: "varunsridharan/action-hashnode-blog@main"
        with:
          USERNAME: "@iamyuvi" # Hashnode Username
          BLOG_URL: "https://bytecorner.dev/" # Blog URL
          COUNT: 3 # MAX Visisble
        env:
          GITHUB_TOKEN: ${{ secrets.HASHNODE_TOKEN }}
