# This is a basic workflow to help you get started with Actions

name: Hashnode Blog Updater

# Controls when the workflow will run
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  update_blogs:
    name: "Update Blogs"
    runs-on: ubuntu-latest
    steps:
      - name: "📥  Fetching Repository Contents"
        uses: actions/checkout@main

      - name: "📚  Hashnode Updater"
        uses: "varunsridharan/action-hashnode-blog@main"
        with:
          USERNAME: 'iamyuvi' # Hashnode Username
          BLOG_URL: 'https://yuvichh.hashnode.dev/' # Blog URL
          COUNT: 10 # MAX Visisble
        env:
          GITHUB_TOKEN: ${{ secrets.HASHNODE_TOKEN }}
