name: "📚 Hashnode Blog Updater"

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *' # Runs Every Day

jobs:
  update_blogs:
    name: "Update Blogs"
    runs-on: ubuntu-latest
    steps:
      - name: "📥  Fetching Repository Contents"
        uses: actions/checkout@main

      - name: "📥  blog-left"
        uses: "HohShenYien/action-hashnode-blog@main"
        with:
          USERNAME: 'iamyuvi'
          BLOG_URL: 'https://yuvichh.hashnode.dev/'
          COUNT: 5
          FILE: "README.md"
          STYLE: "blog-left"
          USE_CANONICAL_URL: "true"
          USE_CUSTOM_BLOG_URL: "true"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
