name: "📚 latest Blog"

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */24 * * *" # Runs Every 24 Hours

jobs:
  update_blogs:
    name: "Update With Latest Blogs"
    runs-on: ubuntu-latest
    steps:
      - name: "📥  Fetching Repository Contents"
        uses: actions/checkout@main

      - name: "📚  Hashnode Updater"
        uses: "varunsridharan/action-hashnode-blog@1.1.1"
        with:
          USERNAME: "iamyuvi" # Hashnode Username
          COUNT: 3 # MAX Visisble
          STYLE: "blog-left"
          BLOG_URL: "https://yuvichh.hashnode.dev/"
        env:
          GITHUB_TOKEN: ${{ secrets.HASHNODE_TOKEN }}
